### PR TITLE
Export JWKS

### PR DESCRIPTION
**Pull request by klimisa**
It is extremely useful to export the JWKS in order to use it directly and not only via nock.

### CODE REVIEW

**Comment by klimisa** [comment]
I'm running the tests locally and they seem to pass.
```λ yarn test
yarn run v1.19.1
$ tape -r ts-node/register '**/__tests__/**/*.{js,ts}'
Done in 0.45s.

**Comment by Levino** [comment]
Dear @klimisa thank you for your contribution. As I have learned now it is not very obvious on how we can all work together in the most efficient form I just added a link to a [best practice guide](https://eli.thegreenplace.net/2019/how-to-send-good-pull-requests-on-github/) for pull requests. Please read it before we proceed.then(() => {
  Please open an issue that describes the problem that you want to solve. And also please add a regression test for your changes.
}).

**Comment by Levino** [comment]
Also, just as a remark: I return as little variables as possible on purpose. Also I do not want to expose any handlers that can be used to alter state. Why I do that is best explained by [Eric Elliot](https://medium.com/javascript-scene/javascript-factory-functions-vs-constructor-functions-vs-classes-2f22ceddf33e).

**Comment by klimisa** [comment]
Hi @Levino, I would like to generate Jwks directly and not using it through nock. I have my own api which needs just a jwks. You already doing that as part of you intercept via nock. I just expose it. I run tests and all pass to me as I said above. I don’t know why.

**Comment by Levino** [comment]
I asked you to add a test and also to add an issue that describes your problem. I think these demands are in order and very simple to follow.
As of now I do not see any benefit from your changes but to clutter the interface.

**Comment by klimisa** [comment]
Not a problem @Levino. Do you want me to close the PR?

**Comment by Levino** [comment]
As I said I would want you to work together with me on this and explain to me why you want these changes. If that is too much to ask, then yes, please close this PR.

**Comment by klimisa** [comment]
I tried to explain twice, what is you don’t understand get and I’m happy further explain it. BTW thank you for the library. It’s awesome!

**Comment by Levino** [comment]
Please go to issues, create an issue and describe your problem in detail. Give some code examples of how you would use the new interface in a real application, or better a test for a real application, I guess.

**Comment by Levino** [comment]
Did you read the blog post I linked? That would be very helpful for all of us.

**Comment by klimisa** [comment]
Ok @Levino I’ll try to create a better PR according to the guidelines. Thank you for your time.

**Pull request closed without merging**
